#!/usr/bin/env python3
"""Plot DRL fault-sensitivity results.

Input:
  results/drl_sensitivity.json

Output:
  results/drl_sensitivity_heatmap.{png,pdf}
  results/drl_sensitivity_table.tex
"""

import argparse
import json
import os
from collections import defaultdict


STRATEGY_LABELS = {
    "ppo": "PPO",
    "gba": "GBA",
    "sa": "SA",
    "ocd": "OCD",
    "random": "Random",
    "static": "Static",
}


def load_rows(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data, data.get("rows", [])


def select_strategy(rows, strategy):
    return [r for r in rows if r.get("strategy") == strategy]


def grid_values(rows, metric):
    kill_vals = sorted({float(r["kill_ratio"]) for r in rows})
    byz_vals = sorted({float(r["byz_ratio"]) for r in rows})
    lookup = {
        (float(r["kill_ratio"]), float(r["byz_ratio"])): float(r.get(metric, 0.0))
        for r in rows
    }
    grid = [[lookup.get((k, b), 0.0) for b in byz_vals] for k in kill_vals]
    return kill_vals, byz_vals, grid


def print_summary(rows):
    grouped = defaultdict(list)
    for row in rows:
        grouped[row["strategy"]].append(row)

    print("\n" + "=" * 92)
    print("DRL FAULT-SENSITIVITY SUMMARY")
    print("=" * 92)
    print(f"{'Strategy':10s} {'Scenarios':>9s} {'Post TPS range':>22s} {'Retention range':>22s} {'Worst case':>20s}")
    print("-" * 92)
    for strategy in sorted(grouped):
        data = grouped[strategy]
        post_vals = [float(r["post_tps_mean"]) for r in data]
        ret_vals = [float(r["retention_mean"]) * 100.0 for r in data]
        worst = min(data, key=lambda r: float(r["post_tps_mean"]))
        print(
            f"{STRATEGY_LABELS.get(strategy, strategy):10s} "
            f"{len(data):9d} "
            f"{min(post_vals):8.1f}--{max(post_vals):8.1f} "
            f"{min(ret_vals):8.1f}--{max(ret_vals):8.1f}% "
            f"k={float(worst['kill_ratio'])*100:.0f}%, b={float(worst['byz_ratio'])*100:.0f}%"
        )
    print("=" * 92)


def write_latex_table(rows, output_dir, strategy="ppo"):
    data = select_strategy(rows, strategy)
    if not data:
        return
    kill_vals = sorted({float(r["kill_ratio"]) for r in data})
    byz_vals = sorted({float(r["byz_ratio"]) for r in data})
    lookup = {
        (float(r["kill_ratio"]), float(r["byz_ratio"])): r
        for r in data
    }
    path = os.path.join(output_dir, "drl_sensitivity_table.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by analysis/plot-drl-sensitivity.py\n")
        f.write("\\begin{table*}[t]\n")
        f.write("\\caption{PPO fault-sensitivity sweep over physical node-kill and active Byzantine ratios. Each cell reports mean post-disaster TPS with retention percentage in parentheses.}\n")
        f.write("\\label{tab:drl_sensitivity}\n")
        f.write("\\centering\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{@{}l" + "r" * len(byz_vals) + "@{}}\n")
        f.write("\\toprule\n")
        header = "Kill ratio"
        for byz in byz_vals:
            header += f" & Byz {byz*100:.0f}\\%"
        f.write(header + " \\\\\n")
        f.write("\\midrule\n")
        for kill in kill_vals:
            cells = [f"{kill*100:.0f}\\%"]
            for byz in byz_vals:
                row = lookup.get((kill, byz))
                if row:
                    cells.append(
                        f"{float(row['post_tps_mean']):.0f} "
                        f"({float(row['retention_mean'])*100:.1f}\\%)"
                    )
                else:
                    cells.append("--")
            f.write(" & ".join(cells) + " \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table*}\n")
    print(f"Saved: {path}")


def plot_heatmaps(rows, output_dir, strategy="ppo"):
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("[WARN] matplotlib not installed; skipping plots.")
        return

    data = select_strategy(rows, strategy)
    if not data:
        print(f"[WARN] No rows for strategy={strategy}; skipping plot.")
        return

    kill_vals, byz_vals, post_grid = grid_values(data, "post_tps_mean")
    _, _, ret_grid = grid_values(data, "retention_mean")
    post_arr = np.array(post_grid)
    ret_arr = np.array(ret_grid) * 100.0

    fig, axes = plt.subplots(1, 2, figsize=(12.8, 4.8), constrained_layout=True)
    fig.suptitle(
        f"{STRATEGY_LABELS.get(strategy, strategy)} Fault-Sensitivity Sweep",
        fontsize=13,
        fontweight="bold",
    )

    for ax, arr, title, cmap, fmt, suffix in [
        (axes[0], post_arr, "Post-Disaster TPS", "viridis", ".0f", ""),
        (axes[1], ret_arr, "Retention (%)", "magma", ".1f", "%"),
    ]:
        im = ax.imshow(arr, aspect="auto", cmap=cmap)
        ax.set_xticks(range(len(byz_vals)))
        ax.set_xticklabels([f"{b*100:.0f}%" for b in byz_vals])
        ax.set_yticks(range(len(kill_vals)))
        ax.set_yticklabels([f"{k*100:.0f}%" for k in kill_vals])
        ax.set_xlabel("Active Byzantine ratio")
        ax.set_ylabel("Physical node-kill ratio")
        ax.set_title(title)
        for i in range(arr.shape[0]):
            for j in range(arr.shape[1]):
                ax.text(
                    j, i, f"{arr[i, j]:{fmt}}{suffix}",
                    ha="center", va="center",
                    color="white" if arr[i, j] < arr.max() * 0.62 else "black",
                    fontsize=8.5,
                    fontweight="bold",
                )
        fig.colorbar(im, ax=ax, shrink=0.88)

    for ext in ("png", "pdf"):
        out = os.path.join(output_dir, f"drl_sensitivity_heatmap.{ext}")
        fig.savefig(out, dpi=180, bbox_inches="tight")
        print(f"Saved: {out}")
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=os.path.join("results", "drl_sensitivity.json"))
    parser.add_argument("--strategy", default="ppo")
    parser.add_argument("--no-plot", action="store_true")
    args = parser.parse_args()

    data, rows = load_rows(args.input)
    if not rows:
        raise SystemExit(f"[ERROR] No rows in {args.input}")

    output_dir = os.path.dirname(os.path.abspath(args.input)) or "."
    print_summary(rows)
    write_latex_table(rows, output_dir, strategy=args.strategy)
    if not args.no_plot:
        plot_heatmaps(rows, output_dir, strategy=args.strategy)


if __name__ == "__main__":
    main()
